---
title: "Prophet Project"
author: "Connor Tomchin"
date: "2024-11-11"
output: html_document
---

```{r}
library(httr2)

api_key <- "C7EO8WAEDCA0JLR2"

ticker <- "IBM"

link <- glue::glue(
  "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={ticker}&apikey={api_key}&outputsize=full&datatype=csv"
  )

ibm_request <- request(link) %>% 
  req_perform()

ibm_daily_return <- read.delim(text = resp_body_string(ibm_request), sep = ",")

```



```{r}
library(prophet)
```


```{r}
library(dplyr)
ibm_daily_return <- ibm_daily_return %>% rename(ds = timestamp)
ibm_daily_return <-ibm_daily_return %>% rename(y = close)

ibm_daily_return$cap <- 240
m <- prophet(ibm_daily_return, yearly.seasonality = TRUE, weekly.seasonality = TRUE)
print(max(ibm_daily_return$y, na.rm = TRUE))

```

```{r}

future <- make_future_dataframe(m, periods = 1000)
future$cap <- 240
fcst <- predict(m, future)
plot(m, fcst)
```

```{r}
library(httr2)

api_key <- "C7EO8WAEDCA0JLR2"

ticker <- "AAPL"

link <- glue::glue(
  "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={ticker}&apikey={api_key}&outputsize=full&datatype=csv"
  )

AAPL_request <- request(link) %>% 
  req_perform()

AAPL_daily_return <- read.delim(text = resp_body_string(AAPL_request), sep = ",")
```


```{r}
library(dplyr)
AAPL_daily_return <- AAPL_daily_return %>% rename(ds = timestamp)
AAPL_daily_return <-AAPL_daily_return %>% rename(y = close)

AAPL_daily_return$cap <- 237.49
m2 <- prophet(AAPL_daily_return, yearly.seasonality = TRUE, weekly.seasonality = TRUE)
```

```{r}
future2 <- make_future_dataframe(m2, periods = 1000)
future2$cap <- 240
fcst <- predict(m2, future2)
plot(m2, fcst)
```


```{r}
IBM_Goldmine <- read.csv("~/Desktop/GoldmineIBM.csv")
```

```{r}
IBM_Goldmine <- IBM_Goldmine %>% rename(ds = DATE)
IBM_Goldmine <-IBM_Goldmine %>% rename(y = avg_buy_price_LR)
```
```{r}
IBM_Goldmine$cap <- 240
m5 <- prophet(IBM_Goldmine, yearly.seasonality = TRUE, weekly.seasonality = TRUE)
```
```{r}
future5 <- make_future_dataframe(m5, periods = 500)
future5$cap <- 240
fcst <- predict(m5, future5)
plot(m5, fcst)
```







